

ALTER TABLE "DIMGR"."COLUMNS" DROP CONSTRAINT "SYS_C0040457"
/
ALTER TABLE "DIMGR"."INTER_TABLE_CONS_REF_TABLES" DROP CONSTRAINT "SYS_C0040459"
/
ALTER TABLE "DIMGR"."TABLE_CONSTRAINTS" DROP CONSTRAINT "SYS_C0040461"
/
ALTER TABLE "DIMGR"."TUPLES" DROP CONSTRAINT "SYS_C0040466"
/
CREATE TABLE "DIMGR"."TABLES_3DD2CE1F9DFA41389AA002F"(
  "OWNER" Varchar2(30 ),
  "TABLE_NAME" Varchar2(30 ),
  "TABLE_DESC" Varchar2(150 ),
  "TABLE_COMMENT" Varchar2(500 ),
  "TABLE_TYPE" Varchar2(20 )
)
/
INSERT INTO "DIMGR"."TABLES_3DD2CE1F9DFA41389AA002F" ("OWNER", "TABLE_NAME", "TABLE_DESC", "TABLE_COMMENT", "TABLE_TYPE") SELECT "OWNER", "TABLE_NAME", "TABLE_DESC", "TABLE_COMMENT", "TABLE_TYPE" FROM "DIMGR"."TABLES"
/



DROP TABLE "DIMGR"."TABLES"
/
ALTER TABLE "DIMGR"."TABLES_3DD2CE1F9DFA41389AA002F" RENAME TO "TABLES"
/


ALTER TABLE "DIMGR"."TABLES" MODIFY ("OWNER" CONSTRAINT "SYS_C0040442" NOT NULL)
/
ALTER TABLE "DIMGR"."TABLES" MODIFY ("TABLE_NAME" CONSTRAINT "SYS_C0040443" NOT NULL)
/

CREATE UNIQUE INDEX "DIMGR"."XPKTABLES" ON "DIMGR"."TABLES" ("OWNER","TABLE_NAME")
/

ALTER TABLE "DIMGR"."TABLES" ADD CONSTRAINT "SYS_C0040444" PRIMARY KEY ("OWNER","TABLE_NAME")
   USING INDEX "DIMGR"."XPKTABLES"
/

COMMENT ON COLUMN "DIMGR"."TABLES"."TABLE_DESC" IS 'Records the description of the table.'
/

COMMENT ON COLUMN "DIMGR"."TABLES"."TABLE_TYPE" IS 'FACT  DIMENSION ACTIVITY SNAPSHOT'
/


ALTER TABLE "DIMGR"."COLUMNS" ADD CONSTRAINT "SYS_C0040457" FOREIGN KEY ("OWNER", "TABLE_NAME") REFERENCES "DIMGR"."TABLES" ("OWNER", "TABLE_NAME")
/


ALTER TABLE "DIMGR"."INTER_TABLE_CONS_REF_TABLES" ADD CONSTRAINT "SYS_C0040459" FOREIGN KEY ("OWNER", "TABLE_NAME") REFERENCES "DIMGR"."TABLES" ("OWNER", "TABLE_NAME")
/


ALTER TABLE "DIMGR"."TABLE_CONSTRAINTS" ADD CONSTRAINT "SYS_C0040461" FOREIGN KEY ("OWNER", "TABLE_NAME") REFERENCES "DIMGR"."TABLES" ("OWNER", "TABLE_NAME")
/


ALTER TABLE "DIMGR"."TUPLES" ADD CONSTRAINT "SYS_C0040466" FOREIGN KEY ("OWNER", "TABLE_NAME") REFERENCES "DIMGR"."TABLES" ("OWNER", "TABLE_NAME")
/
