
--DROP INDEX "DIMGR"."XPKINTER_TABLE_CONSTRAINTS"
/

ALTER TABLE "DIMGR"."INTER_TABLE_CONSTRAINTS" ADD
(
   "REF_PKOWNER" Varchar2(30 ),
   "REF_PKTABLE_NAME" Varchar2(30 ),
   "REF_PKCONSTRAINT_NAME" Varchar2(50 )
)
/
--CREATE UNIQUE INDEX "XPKINTER_TABLE_CONSTRAINTS" ON "DIMGR"."INTER_TABLE_CONSTRAINTS" ("OWNER","TABLE_NAME","CONSTRAINT_NAME")
/
ALTER TABLE "DIMGR"."INTER_TABLE_CONSTRAINTS" ADD CONSTRAINT "FK_REFS_PKCON" FOREIGN KEY ("REF_PKOWNER", "REF_PKTABLE_NAME", "REF_PKCONSTRAINT_NAME") REFERENCES "DIMGR"."TABLE_CONSTRAINTS" ("OWNER", "TABLE_NAME", "CONSTRAINT_NAME")
/
