
ALTER TABLE "DIMGR"."TABLE_CONSTRAINTS" DROP CONSTRAINT "SYS_C0040462"
/

ALTER TABLE "DIMGR"."INTER_TABLE_CONSTRAINTS" DROP CONSTRAINT "SYS_C0040460"
/


ALTER TABLE "DIMGR"."COLUMNS" DROP CONSTRAINT "SYS_C0040457"
/
ALTER TABLE "DIMGR"."INTER_TABLE_CONS_REF_TABLES" DROP CONSTRAINT "SYS_C0040459"
/
ALTER TABLE "DIMGR"."TABLE_CONSTRAINTS" DROP CONSTRAINT "SYS_C0040461"
/
ALTER TABLE "DIMGR"."TUPLES" DROP CONSTRAINT "SYS_C0040466"
/
CREATE TABLE "DIMGR"."TABLES_1FBE561369F84C549216EFB"(
  "OWNER" Varchar2(30 ),
  "TABLE_NAME" Varchar2(30 ),
  "TABLE_DESC" Varchar2(30 ),
  "TABLE_COMMENT" Varchar2(500 ),
  "TABLE_TYPE" Varchar2(20 )
)
/
INSERT INTO "DIMGR"."TABLES_1FBE561369F84C549216EFB" ("OWNER", "TABLE_NAME", "TABLE_DESC", "TABLE_COMMENT", "TABLE_TYPE") SELECT "OWNER", "TABLE_NAME", "TABLE_DESC", "TABLE_COMMENT", "TABLE_TYPE" FROM "DIMGR"."TABLES"
/



ALTER TABLE "DIMGR"."TUPLE_CONSTRAINTS_REF_COLUMNS" DROP CONSTRAINT "SYS_C0040465"
/
CREATE TABLE "DIMGR"."COLUMNS_B4DC68A030514599AB51D4"(
  "OWNER" Varchar2(30 ),
  "TABLE_NAME" Varchar2(30 ),
  "COLUMN_NAME" Varchar2(30 ),
  "COLUMN_ID" Number,
  "DATA_TYPE" Varchar2(106 ),
  "DATA_LENGTH" Number,
  "DATA_PRECISION" Number,
  "DATA_SCALE" Number,
  "COLUMN_DESC" Varchar2(100 ),
  "COLUMN_COMMENT" Varchar2(500 ),
  "NULLABLE" Varchar2(1 ),
  "CONSTRAINT_DESC" Varchar2(500 ),
  "CONSTRAINT_CHECK_CONDITION" Clob,
  "CONSTRAINT_VALIDATION_QRY" Clob,
  "CONSTRAINT_NAME" Varchar2(500 )
)
/
INSERT INTO "DIMGR"."COLUMNS_B4DC68A030514599AB51D4" ("OWNER", "TABLE_NAME", "COLUMN_NAME", "COLUMN_ID", "DATA_TYPE", "DATA_LENGTH", "DATA_PRECISION", "DATA_SCALE", "COLUMN_DESC", "COLUMN_COMMENT", "NULLABLE", "CONSTRAINT_DESC", "CONSTRAINT_CHECK_CONDITION", "CONSTRAINT_VALIDATION_QRY", "CONSTRAINT_NAME") SELECT "OWNER", "TABLE_NAME", "COLUMN_NAME", "COLUMN_ID", "DATA_TYPE", "DATA_LENGTH", "DATA_PRECISION", "DATA_SCALE", "COLUMN_DESC", "COLUMN_COMMENT", "NULLABLE", "CONSTRAINT_DESC", "CONSTRAINT_CHECK_CONDITION", "CONSTRAINT_VALIDATION_QRY", "CONSTRAINT_NAME" FROM "DIMGR"."COLUMNS"
/



DROP TABLE "DIMGR"."COLUMNS"
/
ALTER TABLE "DIMGR"."COLUMNS_B4DC68A030514599AB51D4" RENAME TO "COLUMNS"
/


ALTER TABLE "DIMGR"."COLUMNS" MODIFY ("OWNER" CONSTRAINT "SYS_C0040423" NOT NULL)
/
ALTER TABLE "DIMGR"."COLUMNS" MODIFY ("TABLE_NAME" CONSTRAINT "SYS_C0040424" NOT NULL)
/
ALTER TABLE "DIMGR"."COLUMNS" MODIFY ("COLUMN_NAME" CONSTRAINT "SYS_C0040426" NOT NULL)
/
ALTER TABLE "DIMGR"."COLUMNS" MODIFY ("COLUMN_ID" CONSTRAINT "SYS_C0040425" NOT NULL)
/
ALTER TABLE "DIMGR"."COLUMNS" MODIFY ("DATA_TYPE" CONSTRAINT "SYS_C0040427" NOT NULL)
/
ALTER TABLE "DIMGR"."COLUMNS" MODIFY ("NULLABLE" CONSTRAINT "SYS_C0040428" NOT NULL)
/
ALTER TABLE "DIMGR"."COLUMNS" MODIFY ("NULLABLE" CONSTRAINT "CHECK_NULLABLE_COL" CHECK (nullable in ('Y', 'N')))
/

CREATE INDEX "DIMGR"."XIF1COLUMNS" ON "DIMGR"."COLUMNS" ("OWNER","TABLE_NAME")
/

CREATE UNIQUE INDEX "DIMGR"."XPKCOLUMNS" ON "DIMGR"."COLUMNS" ("OWNER","TABLE_NAME","COLUMN_NAME")
/

ALTER TABLE "DIMGR"."COLUMNS" ADD CONSTRAINT "SYS_C0040429" PRIMARY KEY ("OWNER","TABLE_NAME","COLUMN_NAME")
   USING INDEX "DIMGR"."XPKCOLUMNS"
/

COMMENT ON TABLE "DIMGR"."COLUMNS" IS 'This table records the column-level constraints'
/

COMMENT ON COLUMN "DIMGR"."COLUMNS"."DATA_LENGTH" IS 'Length of the column (in bytes)'
/

COMMENT ON COLUMN "DIMGR"."COLUMNS"."CONSTRAINT_CHECK_CONDITION" IS 'Check constraint condition, without the CHECK keyword'
/

ALTER TABLE "DIMGR"."CONSTRAINT_TYPES" ADD
(
   "COMMENT" Varchar2(500 )
)
/

DROP TABLE "DIMGR"."TABLES"
/
ALTER TABLE "DIMGR"."TABLES_1FBE561369F84C549216EFB" RENAME TO "TABLES"
/


ALTER TABLE "DIMGR"."TABLES" MODIFY ("OWNER" CONSTRAINT "SYS_C0040442" NOT NULL)
/
ALTER TABLE "DIMGR"."TABLES" MODIFY ("TABLE_NAME" CONSTRAINT "SYS_C0040443" NOT NULL)
/

CREATE UNIQUE INDEX "DIMGR"."XPKTABLES" ON "DIMGR"."TABLES" ("OWNER","TABLE_NAME")
/

ALTER TABLE "DIMGR"."TABLES" ADD CONSTRAINT "SYS_C0040444" PRIMARY KEY ("OWNER","TABLE_NAME")
   USING INDEX "DIMGR"."XPKTABLES"
/

COMMENT ON COLUMN "DIMGR"."TABLES"."TABLE_DESC" IS 'Records the description of the table.'
/

COMMENT ON COLUMN "DIMGR"."TABLES"."TABLE_TYPE" IS 'FACT  DIMENSION ACTIVITY SNAPSHOT'
/



CREATE TABLE "TABLE_CONSTRAINTS_REF_COLUMNS"(
  "OWNER" Varchar2(30 ) NOT NULL,
  "TABLE_NAME" Varchar2(30 ) NOT NULL,
  "CONSTRAINT_NAME" Varchar2(20 ) NOT NULL,
  "COLUMN_NAME" Varchar2(30 ) NOT NULL
)
/

ALTER TABLE "TABLE_CONSTRAINTS_REF_COLUMNS" ADD CONSTRAINT "Key4" PRIMARY KEY ("OWNER","TABLE_NAME","CONSTRAINT_NAME","COLUMN_NAME")
/



CREATE TABLE "ITABLE_CONSTRAINTS_REF_COLUMNS"(
  "OWNER" Varchar2(30 ) NOT NULL,
  "TABLE_NAME" Varchar2(30 ) NOT NULL,
  "CONSTRAINT_NAME" Varchar2(20 ) NOT NULL,
  "COLUMN_NAME" Varchar2(30 ) NOT NULL
)
/

ALTER TABLE "ITABLE_CONSTRAINTS_REF_COLUMNS" ADD CONSTRAINT "Key5" PRIMARY KEY ("CONSTRAINT_NAME","OWNER","TABLE_NAME","COLUMN_NAME")
/

ALTER TABLE "DIMGR"."INTER_TABLE_CONSTRAINTS" ADD CONSTRAINT "IT_CON_HAS_TYPE" FOREIGN KEY ("TYPE") REFERENCES "DIMGR"."CONSTRAINT_TYPES" ("TYPE") ON DELETE SET NULL
/
ALTER TABLE "DIMGR"."TABLE_CONSTRAINTS" ADD CONSTRAINT "T_CON_HAS_TYPE" FOREIGN KEY ("TYPE") REFERENCES "DIMGR"."CONSTRAINT_TYPES" ("TYPE") ON DELETE SET NULL
/
ALTER TABLE "TABLE_CONSTRAINTS_REF_COLUMNS" ADD CONSTRAINT "T_CON_REF_COLS" FOREIGN KEY ("OWNER", "TABLE_NAME", "CONSTRAINT_NAME") REFERENCES "DIMGR"."TABLE_CONSTRAINTS" ("OWNER", "TABLE_NAME", "CONSTRAINT_NAME")
/
ALTER TABLE "TABLE_CONSTRAINTS_REF_COLUMNS" ADD CONSTRAINT "COL_IS_REFBY_TCON" FOREIGN KEY ("OWNER", "TABLE_NAME", "COLUMN_NAME") REFERENCES "DIMGR"."COLUMNS" ("OWNER", "TABLE_NAME", "COLUMN_NAME")
/
ALTER TABLE "ITABLE_CONSTRAINTS_REF_COLUMNS" ADD CONSTRAINT "IT_CON_REF_COLS" FOREIGN KEY ("CONSTRAINT_NAME") REFERENCES "DIMGR"."INTER_TABLE_CONSTRAINTS" ("CONSTRAINT_NAME")
/
ALTER TABLE "ITABLE_CONSTRAINTS_REF_COLUMNS" ADD CONSTRAINT "COL_IS_REFBY_ITCON" FOREIGN KEY ("OWNER", "TABLE_NAME", "COLUMN_NAME") REFERENCES "DIMGR"."COLUMNS" ("OWNER", "TABLE_NAME", "COLUMN_NAME")
/

COMMENT ON TABLE "DIMGR"."CONSTRAINT_TYPES" IS 'Type of the constraint (table-level or inter-table-level): PK, FK, UNIQUE, TABLE-LEVEL, INTER-TABLE-LEVEL'
/

ALTER TABLE "DIMGR"."COLUMNS" ADD CONSTRAINT "SYS_C0040457" FOREIGN KEY ("OWNER", "TABLE_NAME") REFERENCES "DIMGR"."TABLES" ("OWNER", "TABLE_NAME")
/


ALTER TABLE "DIMGR"."INTER_TABLE_CONS_REF_TABLES" ADD CONSTRAINT "SYS_C0040459" FOREIGN KEY ("OWNER", "TABLE_NAME") REFERENCES "DIMGR"."TABLES" ("OWNER", "TABLE_NAME")
/


ALTER TABLE "DIMGR"."TABLE_CONSTRAINTS" ADD CONSTRAINT "SYS_C0040461" FOREIGN KEY ("OWNER", "TABLE_NAME") REFERENCES "DIMGR"."TABLES" ("OWNER", "TABLE_NAME")
/


ALTER TABLE "DIMGR"."TUPLE_CONSTRAINTS_REF_COLUMNS" ADD CONSTRAINT "SYS_C0040465" FOREIGN KEY ("OWNER", "TABLE_NAME", "COLUMN_NAME") REFERENCES "DIMGR"."COLUMNS" ("OWNER", "TABLE_NAME", "COLUMN_NAME")
/


ALTER TABLE "DIMGR"."TUPLES" ADD CONSTRAINT "SYS_C0040466" FOREIGN KEY ("OWNER", "TABLE_NAME") REFERENCES "DIMGR"."TABLES" ("OWNER", "TABLE_NAME")
/
