/*
 Create DB links from dev to Test fro DI Mgr
*/

-- old dblink
--
-- TARGET_DW_TEST  (Database Link) 
--
CREATE PUBLIC DATABASE LINK TARGET_DW_TEST
 CONNECT TO TARGET_DW
 IDENTIFIED BY <PWD>
 USING 'DWH01TEST'
/

drop public database link TARGET_DW_TEST
/

-- dblink to TARGET_DW
CREATE PUBLIC DATABASE LINK  TARGET_DW_TEST
 CONNECT TO TARGET_DW
 IDENTIFIED BY target_dw
 USING '(DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 10.101.3.50)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = DWH01)
    )
  )'
/

drop public database link  PRESENT_PERIF_TEST
/
-- dblink to PRESENT_PERIF
CREATE PUBLIC DATABASE LINK  PRESENT_PERIF_TEST
 CONNECT TO PRESENT_PERIF
 IDENTIFIED BY PRESENT_PERIF
 USING ' (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 10.101.3.50)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = DWH01)
    )
  )'
/