INSERT INTO CONSTRAINT_TYPES ( TYPE, TYPE_DESC, "COMMENT" ) VALUES ( 
'U', 'unique key', NULL); 
INSERT INTO CONSTRAINT_TYPES ( TYPE, TYPE_DESC, "COMMENT" ) VALUES ( 
'P', 'primary key', NULL); 
INSERT INTO CONSTRAINT_TYPES ( TYPE, TYPE_DESC, "COMMENT" ) VALUES ( 
'R', 'referential integrity', NULL); 
INSERT INTO CONSTRAINT_TYPES ( TYPE, TYPE_DESC, "COMMENT" ) VALUES ( 
'TC', 'generic table constraint', NULL); 
INSERT INTO CONSTRAINT_TYPES ( TYPE, TYPE_DESC, "COMMENT" ) VALUES ( 
'ITC', 'generic inter-table constraint', NULL); 
COMMIT;
